Adding missing instruments
bitbankinc/java-bitbankcc pull request #3
Opened 2018-02-05 16:22 UTC by m4ce

As per https://docs.bitbank.cc, I am adding a number of missing instruments. As I am relying on your Java API to interact with your backend, it'd be great if you could make a release out of it..

2018-02-05 17:37 UTC, m4ce commented
I've also fixed the Transaction class where price and amounts are actually strings..

2018-02-16 03:27 UTC, junderw requested changes
1. Adding CurrencyPairs
2. Changing from int and BigDecimal to String x 2

These are ok. Everything else, please separate into a new pull request.

In general, "Minor Improvements" with a lot of changes are less likely to get merged. Each pull request should have an explicit purpose.

Thanks.

2018-02-16 03:27 UTC, junderw commented on src/main/java/cc/bitbank/entity/Depth.java
> +    private BigDecimal[][] asks;
Please refrain from changing the interfaces if not necessary.

2018-02-16 03:27 UTC, junderw commented on src/main/java/cc/bitbank/entity/Transactions.java
> +        private String price;
Keep it public.
Change to String is ok.

2018-02-16 03:27 UTC, junderw commented on src/main/java/cc/bitbank/entity/Transactions.java
> +        private String amount;
Keep it public.
Change to String is ok.

2018-02-16 03:27 UTC, junderw commented on src/main/java/cc/bitbank/entity/Transactions.java
> +    public Transaction[] getTransactions() {
Please remove along with all the other new methods. (this should be a separate pull request)

2018-02-16 03:27 UTC, junderw commented on src/main/java/cc/bitbank/entity/enums/CurrencyPair.java
> +    XRP_JPY("xrp_jpy"),
Thanks for this!

2018-02-16 03:58 UTC, junderw approved these changes
nvm got the OK to just approve everything.

2018-02-16 03:58 UTC, merged

2018-02-16 08:30 UTC, m4ce commented
Thank you! We have other changes coming up. We will make a separate PR for these.